---
apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
  labels:
    service_name: clusterip
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: clusterip-service