---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-and-alpine-deployment
  labels:
    stage: dev
spec:
  selector:
    matchLabels:
      pod: web-service
  template:
     metadata:
       name: web-service-test
       labels:
         pod: web-service
     spec:
      containers:
        - name: web-container
          ports:
            - containerPort: 80
          image: nginx
          imagePullPolicy: IfNotPresent
        - name: alpine-container
          ports:
            - containerPort: 22
          image: alpine
          imagePullPolicy: IfNotPresent
          command: ["sleep", "150000"]
  replicas: 6

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-for-web-deploy
  labels:
    stage_service: dev-web
spec:
  selector:
    pod: web-service
  clusterIP: 10.96.0.45
  ports:
    - name: web-container
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-for-alpine-deploy
  labels:
    stage_service: dev-alpine
spec:
  selector:
    pod: web-service
  clusterIP: 10.96.0.48
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: alpine-container
  type: ClusterIP