apiVersion: v1
kind: Service
metadata:
  name: nodeport
  labels:
    service_name: nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30027
      name: web-service-5
  selector:
    name: ha-web-service