---
apiVersion: v1
kind: Pod
metadata:
  name: web-service-11
  labels:
    web_service: name11
    category: web
spec:
  containers:
    - name: web-container-11
      image: nginx:alpine
      imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30025
      name: web-port
  selector:
    web_service: name11