---
# nginx-logs-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-logs-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Retain
  nfs:  # or hostPath or other supported storage
    path: /k8s/data/nginx-logs
    server: 172.16.7.99
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi


---
# nginx-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: logs
          mountPath: /var/log/nginx
  volumes:
    - name: logs
      persistentVolumeClaim:
        claimName: nginx-logs-pvc


