---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-volume
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /k8s/data/nginx-core
    server: 172.16.7.99

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv-pod
  labels:
    web-server: nginx
spec:
  volumes:
    - name: nginx-pv-storage
      persistentVolumeClaim:
        claimName: nginx-pv-claim
  containers:
    - name: nginx-web-container
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-pv-storage

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    web-server: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort