---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-html-pv
  labels:
    storage_html: nfs
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /k8s/data/nginx-core
    server: 172.16.7.99

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-logs-pv
  labels:
    storage_logs: nfs
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /k8s/data/nginx-logs
    server: 172.16.7.99

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-html-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 7Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 280Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-web-container
  labels:
    web: nginx_new
spec:
  volumes:
    - name: nginx-html-storage
      persistentVolumeClaim:
        claimName: nginx-html-pvc
    - name: nginx-logs-storage
      persistentVolumeClaim:
        claimName: nginx-logs-pvc
  containers:
    - name: nginx-container-with-pv
      imagePullPolicy: IfNotPresent
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-html-storage
        - mountPath: "/var/log/nginx"
          name: nginx-logs-storage

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    web: nginx_new
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090
  type: NodePort