---
apiVersion: v1
kind: Pod
metadata:
  name: resource-allocation-pod
  labels:
    pod: resource_allocation
spec:
  containers:
    - name: ngnix-container
      image: nginx
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "10Mi"
          cpu: "250m"
        limits:
          memory: "30Mi"
          cpu: "750m"

    - name: redis-container
      imagePullPolicy: Always
      image: redis
      ports:
        - containerPort: 6379
      resources:
        requests:
          cpu: "250m"
          memory: "10Mi"
        limits:
          cpu: "750m"
          memory: "30Mi"