---
- name: Setup the k8s master node for cluster.
  hosts: k8s-masters
  gather_facts: true
  tasks:

    - name: Update the '/etc/hosts' file
      ansible.builtin.copy:
        src: ./data_files/local_hosts
        dest: /etc/hosts
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: Create "/etc/apt/keyrings" directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
        owner: "root"
        group: "root"

    - name: Download Kubernetes APT key
      apt_key:
        url: "https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key"
        keyring: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
        state: present
        # mode: "0644"
        # owner: "root"
        # group: "root"

    - name: Update the source files
      copy:
        src: ./data_files/kubernetes.list
        dest: /etc/apt/sources.list.d/kubernetes.list
        mode: "0644"
        owner: "root"
        group: "root"


    - name: Update with latest repo
      apt:
        update_cache: yes

    - name: Install the Kubernetes packages for master node
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
    
    - name: Remove swap entry from /etc/fstab
      mount:
        name: swap
        fstype: swap
        state: absent

    - name: Load the required modules
      copy:
        src: ./data_files/k8s.conf
        dest: /etc/modules-load.d/k8s.conf
        mode: "0644"
        owner: "root"
        group: "root"

