apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-webpage
  namespace: dev
  labels:
    service_type: webpage
  annotations:
    buildversion: "3.5"
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: web-container
          image: nginx
          imagePullPolicy: IfNotPresent
          
