---
apiVersion: v1
kind: Secret
metadata:
  name: secret-for-a-pod
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "cmVkaGF0MTIzCg=="
  MYSQL_DATABASE: "dGVzdGRhdGFiYXNlCg=="
  MYSQL_USER: "bmF6bXVsCg=="
  MYSQL_PASSWORD: "cmVkaGF0MTIzCg=="


---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
spec:
  containers:
    - name: mysql-container
      imagePullPolicy: Always
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: secret-for-a-pod
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: MYSQL_DATABASE
              name: secret-for-a-pod