---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "helloworld-test"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "helloworld"
  template:
    metadata:
      labels:
        app: "helloworld"
    spec:
      containers:
      - name: "nginx-webserver"
        image: "container-registry.cellosco.pe/sre/nginx:latest"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: "celloscope-harbor-registry-secret"