---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-ram-limitranage-for-containers
  labels:
    limitranages: containers
spec:
  limits:
    - type: Container
      default:            # Hard limit
        cpu: 1
        memory: 200Mi
      defaultRequest:     # Soft limit
        cpu: 0.5
        memory: 100Mi