#SPDX-License-Identifier: MIT-0
---
# handlers file for configuration_for_kubernetes_environment
- name: Restart cloud-init service
  service:
    name: cloud-init
    state: restarted
    enabled: yes

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Load the required modules
  command: modprobe {{ item }}
  loop:
    - br_netfilter
    - overlay

- name: Reload the ip forwarding settings
  sysctl:
    reload: yes
    # sysctl_file: /etc/sysctl.d/10-k8s.conf

- name: Reload the daemons
  systemd:
    daemon_reload: yes

- name: Restart containerd service
  service:
    name: containerd
    state: restarted
    enabled: yes