apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-2
  labels:
    service: ubuntu
spec:
  restartPolicy: Always
  containers:
    - name: ubuntu-sleeper-container-2
      image: ubuntu
      imagePullPolicy: IfNotPresent
      command: ["sleep"]
      args: ["100"]
