apiVersion: v1
kind: Pod
metadata:
  name: web-1
  labels:
    pod: web
spec:
  containers:
    - name: nginx-pod
      image: nginx
      imagePullPolicy: IfNotPresent
    - name: busybox-pod
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "while true; do echo Hello from BusyBox; sleep 10; done"]
