apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx

status:
  conditions:
    - status: "True"
      type: Initialized
      lastProbeTime: null