apiVersion: v1
kind: Pod
metadata:
  name: web-service25
  labels:
    scheduling: manual
    deploy: k8s-worker-2
spec:
  containers:
    - name: web-container
      imagePullPolicy: IfNotPresent
      image: nginx
  nodeName: k8s-worker-2