apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: nginx-container
      imagePullPolicy: IfNotPresent
      image: nginx
  tolerations:
    - key: app
      value: blue
      operator: Equal
      effect: NoSchedule