---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "secret-data"
data:
  DB_Host: "bXlzcWw="
  DB_User: "YWRtaW4="
  DB_Password: "cGFzc3dvcmQ="
  MYSQL_ROOT_PASSWORD: "cGFzc3dvcmQ="
---
apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    db: "mysql"
  name: "mysql-pod"
spec:
  restartPolicy: Always
  containers:
  - name: "mysql"
    image: "mysql"
    imagePullPolicy: "IfNotPresent"
    ports:
    - containerPort: 3306
    envFrom:
    - secretRef:
        name: "secret-data"