---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    stage: prod

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-ns-quota
  namespace: prod
  labels:
    namespace: prod
    stage: prod
spec:
  hard:
    pods: "3"
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi