---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-for-a-pod
data:
  MYSQL_ROOT_PASSWORD: "redhat123"
  MYSQL_DATABASE: "testdatabase"
  MYSQL_USER: "nazmul"
  MYSQL_PASSWORD: "redhat321"


---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-configmap
spec:
  containers:
    - name: mysql-container
      imagePullPolicy: Always
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: configmap-for-a-pod
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: configmap-for-a-pod