---
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-vol2
  labels:
    pod: emptydir_vol_limit
spec:
  volumes:
    - name: vol2
      emptyDir:
        sizeLimit: 1G
  containers:
    - name: nginx-container
      image: nginx
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /shared
          name: vol2

    - name: document2
      imagePullPolicy: Always
      image: ubuntu
      args:
        - sleep
        - "10000"
      volumeMounts:
        - mountPath: /data
          name: vol2