---
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-vol3
  labels:
    pod: emptydir_vol_limit_memory
spec:
  volumes:
    - name: vol3
      emptyDir:
        medium: Memory
        sizeLimit: 1G
  containers:
    - name: nginx-container
      image: nginx
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /shared
          name: vol3

    - name: document3
      imagePullPolicy: Always
      image: ubuntu
      args:
        - sleep
        - "10000"
      volumeMounts:
        - mountPath: /data
          name: vol3