---
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-vol1
  labels:
    pod: emptydir_vol
spec:
  volumes:
    - name: vol1
      emptyDir: {}
  containers:
    - name: nginx-container
      image: nginx
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /data
          name: vol1

    - name: doc1
      imagePullPolicy: Always
      image: ubuntu
      args:
        - sleep
        - "10000"
      volumeMounts:
        - mountPath: /shared
          name: vol1