apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    stage: multi
spec:
  restartPolicy: Always
  containers:
    - name: nginx-web-container
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
    - name: dns-container
      image: ubuntu/bind9
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 53