- name: Update the local hosts file
  blockinfile:
    path: /etc/cloud/templates/hosts.debian.tmpl
    block: |
      # marker: "# {mark} ANSIBLE MANAGED BLOCK"
      172.16.7.91  k8s-master-01
      172.16.7.92  k8s-worker-01
      172.16.7.93  k8s-worker-02
      172.16.7.94  k8s-worker-03
      # marker: "# {mark} ANSIBLE MANAGED BLOCK"
  notify:
    - Restart cloud-init service

- name: Immediately restart cloud init file if hosts entry changed
  meta: flush_handlers
