
- name: Add the GPG key for the Kubernetes repository
  copy:
    src: ./files/kubernetes-apt-keyring.gpg
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    owner: root
    group: root
    mode: '0644'

- name: Add the Kubernetes APT repository
  copy:
    src: ./files/kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: root
    group: root
    mode: '0644'
  notify:
    - Update apt cache

- name: Immediately update apt cache if repo changed
  meta: flush_handlers

- name: Install Kubernetes components for master nodes
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '>=')
    - ansible_distribution_version is version('22.04', '<=')
    - "'k8s_masters' in group_names"

- name: Install Kubernetes components for worker nodes
  apt:
    name:
      - kubelet
      - kubeadm
    state: present
    update_cache: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '>=')
    - ansible_distribution_version is version('22.04', '<=')
    - "'k8s_workers' in group_names"

- name: Disable the swap memory
  command: swapoff -a

- name: Create required modules file
  file:
    path: /etc/modules-load.d/k8s.conf
    state: touch
    owner: root
    group: root
    mode: '0644'
    modification_time: preserve
    access_time: preserve

- name: Load the required modules
  blockinfile:
    path: /etc/modules-load.d/k8s.conf
    block: |
      # Kubernetes modules
      br_netfilter
      overlay
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: yes
    # append_newline: yes
    owner: root
    group: root
    mode: '0644'
  notify:
    - Load the required modules

- name: Immediately load the required modules if changed
  meta: flush_handlers

- name: Create the IP forwarding configuration file
  file:
    path: /etc/sysctl.d/10-k8s.conf
    state: touch
    owner: root
    group: root
    mode: '0644'
    modification_time: preserve
    access_time: preserve

- name: Enable the IP forwording
  blockinfile:
    path: /etc/sysctl.d/10-k8s.conf
    block: |
      # Kubernetes sysctl settings
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-arptables = 1
      net.ipv4.ip_forward = 1
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: yes
    # append_newline: yes
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload the ip forwarding settings

- name: Immediately reload the ip forwarding settings if changed
  meta: flush_handlers

- name: Modify the CGroup driver for kubelet
  replace:
    path: /etc/default/kubelet
    regexp: '^KUBELET_CGROUP_ARGS=.*'
    replace: 'KUBELET_CGROUP_ARGS="--cgroup-driver=systemd"'
    backup: yes
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload the daemons

- name: Immediately reload the daemons if changed
  meta: flush_handlers

- name: Restart the kubelet service
  service:
    name: kubelet
    state: restarted
    enabled: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '>=')
    - ansible_distribution_version is version('22.04', '<=')

- name: Remove the containerd default config file
  file:
    path: /etc/containerd/config.toml
    state: absent
  notify:
    - Restart containerd service

- name: Immediately restart containerd service if changed
  meta: flush_handlers