apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-limit-memory
  labels:
    limit: memory
spec:
  limits:
    - type: Container
      default:
        memory: 1Gi
      defaultRequest:
        memory: 1Gi
      max:
        memory: 1Gi
      min:
        memory: 500Mi