---
apiVersion: v1
kind: Pod
metadata:
  name: web-5
  labels:
    web: nginx
spec:
  containers:
    - name: web-5
      image: nginx
      imagePullPolicy: IfNotPresent
  nodeSelector:
    color: blue