---
apiVersion: v1
kind: Namespace
metadata:
  name: alhua
  labels:
    meeting: alhua


---
apiVersion: v1
kind: Secret
metadata:
  namespace: alhua
  name: secrets-for-wordpress
  labels:
    secret: wordpress
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "cmVkaGF0MTIzCg=="
  MYSQL_DATABASE: "dGVzdGRhdGFiYXNlCg=="
  MYSQL_USER: "bmF6bXVsCg=="
  MYSQL_PASSWORD: "cmVkaGF0MTIzCg=="


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: alhua
  name: wordpress-deployment
  labels:
    dp: wordpress
spec:
  replicas: 100
  selector:
    matchLabels:
      app: web-app-service
  template:
    metadata:
      labels:
        app: web-app-service
    spec:
      containers:
        - name: wordpress-container
          image: wordpress:5.7
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: secrets-for-wordpress
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: secrets-for-wordpress
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: secrets-for-wordpress
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: secrets-for-wordpress


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: alhua
  name: mysql-deployment
  labels:
    deploy: mysql
spec:
  selector:
    matchLabels:
      app: mysql-app-service
  template:
    metadata:
      labels:
        app: mysql-app-service
    spec:
      containers:
        - name: mysql-containers
          imagePullPolicy: Always
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: secrets-for-wordpress
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: secrets-for-wordpress
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: secrets-for-wordpress
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: secrets-for-wordpress



---
apiVersion: v1
kind: Service
metadata:
  namespace: alhua
  name: mysql-service
  labels:
    service_label: mysql
spec:
  type: NodePort
  selector:
    app: mysql-app-service
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30026


---
apiVersion: v1
kind: Service
metadata:
  namespace: alhua
  name: wordpress-service
  labels:
    service_label: wordpress
spec:
  type: NodePort
  selector:
    app: web-app-service
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30029
