---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-vpa
  labels:
    deploy: my-app-vpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-vpa
  template:
    metadata:
      labels:
        app: my-app-vpa
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: 8Mi
            limits:
              cpu: "500m"
              memory: 32Mi

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service-vpa
  labels:
    deploy: my-app-service-vpa
spec:
  selector:
    app: my-app-vpa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30020
  type: NodePort

---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-app-vpa
  labels:
    deploy: my-app-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-vpa
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: nginx-container
        minAllowed:
          cpu: "250m"
        maxAllowed:
          cpu: "2"
        controlledResources: ["cpu"]