---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-test
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      name: my-app
      labels:
        app: blue
    spec:
      containers:
        - name: web-app-container
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
            - resourceName: memory
              restartPolicy: RestartContainer
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "2"
              memory: "512Mi"