apiVersion: v1
kind: Pod
metadata:
  name: hostpath_vol
spec:
  volumes:
    - name: host_vol1
      hostPath:
        path: /mnt/webhost
        type: DirectoryOrCreate
  containers:
    - name: nginx-container
      image: nginx
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: host_vol1
          readOnly: false